version: "1"

services:
  frontend:
    build: ./frontend
    ports:
      - 8080:8080
    volumes:
      - ./frontend:/data
    environment:
      - API_URL=example:port

  server:
    build: ./server
    ports:
      - 8081:8081
    volumes:
      - ./server:/data
    environment:
      - DATABASE_URL=example:port
