version: "3.4"

services:
  frontend:
    build: ./frontend
    ports:
      - 8080:8080
    volumes:
      - ./frontend:/data
    environment:
      - API_URL=http://localhost:8081/
      - NODE_ENV=development
  server:
    build: ./server
    ports:
      - 8081:8081
    volumes:
      - ./server:/data
    environment:
      - DATABASE_URL=example:port
      - NODE_ENV=development

